---
STAGING:
  host: "localhost"
  user: "YOUR_MYSQL_USERNAME"
  password: "YOUR_MYSQL_USER_PASSWORD"
  database: "staging"
  omit_keys: ["_stock", "total_sales", "_manage_stock", "_price"]
  omit_types: ["shop_order", "shop_order_refund", "shop_coupon", "product"]
  omit_tables:  ["wp_users", "wp_usermeta", "wp_options"]

LIVE:
  host: "localhost"
  user: "YOUR_MYSQL_USERNAME"
  password: "YOUR_MYSQL_USER_PASSWORD"
  database: "wp_charlieapple"
  preserve_keys: ["_stock", "total_sales", "_manage_stock", "_price"]
  url: "https://charlieapple.gorenfeld.co.uk"
  migration_url: "https://catestmigrate.wpengine.com"
